<?php

namespace App\Services;

use RuntimeException;

class TreePngExportService
{
    public function export(array $tree, string $paperSize): string
    {
        if (! function_exists('imagecreatetruecolor')) {
            throw new RuntimeException('PNG rendering is unavailable.');
        }
        [$width, $height] = match ($paperSize) {
            'A2' => [7016, 4961], 'A3' => [4961, 3508], default => [3508, 2480]
        };
        $image = imagecreatetruecolor($width, $height);
        $white = imagecolorallocate($image, 255, 255, 255);
        $ink = imagecolorallocate($image, 31, 41, 55);
        $line = imagecolorallocate($image, 148, 163, 184);
        $root = imagecolorallocate($image, 219, 234, 254);
        imagefill($image, 0, 0, $white);
        imagestring($image, 5, 60, 40, 'Bagan Silsilah - '.$tree['mode'], $ink);
        $positions = [];
        $scaleX = ($width - 160) / max($tree['viewport']['width'], 1);
        $scaleY = ($height - 240) / max($tree['viewport']['height'], 1);
        foreach ($tree['nodes'] as $node) {
            $positions[$node['uuid']] = [80 + (int) ($node['position']['x'] * $scaleX), 120 + (int) ($node['position']['y'] * $scaleY)];
        }
        foreach ($tree['edges'] as $edge) {
            [$sourceX, $sourceY] = $positions[$edge['source_uuid']];
            [$targetX, $targetY] = $positions[$edge['target_uuid']];
            imageline($image, $sourceX, $sourceY, $targetX, $targetY, $line);
        }
        foreach ($tree['nodes'] as $node) {
            [$x, $y] = $positions[$node['uuid']];
            $background = $node['is_root'] ? $root : $white;
            imagefilledrectangle($image, $x - 70, $y - 30, $x + 70, $y + 30, $background);
            imagerectangle($image, $x - 70, $y - 30, $x + 70, $y + 30, $ink);
            imagestring($image, 3, $x - 62, $y - 8, substr(($node['is_alive'] ? '' : '+ ').$node['name'], 0, 22), $ink);
        }
        imagestring($image, 3, 60, $height - 60, 'Generated by Family Tree Platform Indonesia', $ink);
        ob_start();
        imagepng($image, null, 6);
        $contents = ob_get_clean();
        imagedestroy($image);
        if (! is_string($contents)) {
            throw new RuntimeException('PNG rendering failed.');
        }

        return $contents;
    }
}
