<x-layouts.app :title="$member ? 'Edit Anggota' : 'Tambah Anggota'">
    <div class="mb-4"><a href="{{ $member ? route('members.show', $member) : route('members.index') }}" class="small">← Kembali</a><h1 class="h2 mt-2 mb-1">{{ $member ? 'Edit '.$member->full_name : 'Tambah anggota' }}</h1><p class="text-secondary mb-0">Lengkapi informasi yang tersedia. Data dapat diperbarui kemudian.</p></div>
    @if($errors->any())<x-alert variant="danger"><strong>Form belum dapat disimpan.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
    <form method="POST" action="{{ $member ? route('members.update', $member) : route('members.store') }}" enctype="multipart/form-data">
        @csrf @if($member) @method('PUT') @endif
        <x-card>
            <ul class="nav nav-tabs mb-4" role="tablist">@foreach(['basic' => 'Info Dasar', 'family' => 'Info Keluarga', 'bio' => 'Biografi', 'photos' => 'Foto', 'documents' => 'Dokumen'] as $id => $label)<li class="nav-item"><button class="nav-link {{ $loop->first ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#{{ $id }}" type="button">{{ $label }}</button></li>@endforeach</ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="basic"><div class="row g-3"><div class="col-md-8"><x-form.input name="full_name" label="Nama lengkap" :value="old('full_name', $member?->full_name)" required /></div><div class="col-md-4"><x-form.input name="nickname" label="Nama panggilan" :value="old('nickname', $member?->nickname)" /></div><div class="col-md-4"><x-form.select name="gender" label="Gender" :options="['' => 'Belum ditentukan', 'male' => 'Laki-laki', 'female' => 'Perempuan']" :selected="old('gender', $member?->gender)" /></div><div class="col-md-4"><x-form.input name="birth_place" label="Tempat lahir" :value="old('birth_place', $member?->birth_place)" /></div><div class="col-md-4"><x-form.input name="birth_date" type="date" label="Tanggal lahir" :value="old('birth_date', $member?->birth_date?->format('Y-m-d'))" /></div></div></div>
                <div class="tab-pane fade" id="family"><div class="row g-3"><div class="col-md-6"><x-form.select name="family_branch_uuid" label="Cabang keluarga" :options="['' => 'Tanpa cabang'] + $branches->pluck('name', 'uuid')->all()" :selected="old('family_branch_uuid', $member?->branch?->uuid)" /></div><div class="col-md-6"><x-form.select name="is_alive" label="Status hidup" :options="['1' => 'Hidup', '0' => 'Wafat']" :selected="old('is_alive', $member === null || $member->is_alive ? '1' : '0')" required /></div><div class="col-md-6"><x-form.input name="death_place" label="Tempat wafat" :value="old('death_place', $member?->death_place)" /></div><div class="col-md-6"><x-form.input name="death_date" type="date" label="Tanggal wafat" :value="old('death_date', $member?->death_date?->format('Y-m-d'))" /></div><p class="small text-secondary mb-0">Tanggal wafat wajib diisi bila status Wafat dipilih.</p></div></div>
                <div class="tab-pane fade" id="bio"><label class="form-label" for="biography">Biografi</label><textarea class="form-control @error('biography') is-invalid @enderror" id="biography" name="biography" rows="8">{{ old('biography', $member?->biography) }}</textarea></div>
                <div class="tab-pane fade" id="photos"><div class="row align-items-center g-3">@if($member)<div class="col-auto">@include('members.partials.avatar', ['member' => $member])</div>@endif<div class="col"><label class="form-label" for="photo">{{ $member?->profile_photo ? 'Ganti' : 'Unggah' }} foto profil</label><input class="form-control @error('photo') is-invalid @enderror" id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp"><div class="form-text">JPG, PNG, atau WebP; maksimal 5 MB. Thumbnail dibuat otomatis.</div></div></div></div>
                <div class="tab-pane fade" id="documents"><x-empty-state title="Belum ada dokumen" message="Arsip dokumen anggota akan tersedia saat modul dokumen diaktifkan." /></div>
            </div>
            <div class="d-flex justify-content-end gap-2 border-top pt-3 mt-4"><a href="{{ route('members.index') }}" class="btn btn-outline-secondary">Batal</a><button class="btn btn-primary" type="submit">{{ $member ? 'Simpan perubahan' : 'Tambah anggota' }}</button></div>
        </x-card>
    </form>
</x-layouts.app>
