<x-layouts.app title="Anggota Keluarga">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h2 mb-1">Anggota {{ $family->name }}</h1><p class="text-secondary mb-0">{{ $members->total() }} anggota dalam keluarga aktif.</p></div>@can('create', [App\Models\FamilyMember::class, $family])<a href="{{ route('members.create') }}" class="btn btn-primary">Tambah anggota</a>@endcan</div>
    @if(session('status'))<x-alert variant="success">{{ session('status') }}</x-alert>@endif
    <x-card title="Cari dan filter" class="mb-4"><form method="GET" action="{{ route('members.index') }}" class="row g-3"><div class="col-lg-4"><x-form.input name="search" label="Nama atau panggilan" :value="$filters['search'] ?? ''" /></div><div class="col-sm-6 col-lg-2"><x-form.select name="gender" label="Gender" :options="['' => 'Semua', 'male' => 'Laki-laki', 'female' => 'Perempuan']" :value="$filters['gender'] ?? ''" /></div><div class="col-sm-6 col-lg-2"><x-form.select name="is_alive" label="Status" :options="['' => 'Semua', '1' => 'Hidup', '0' => 'Wafat']" :value="$filters['is_alive'] ?? ''" /></div><div class="col-sm-6 col-lg-2"><x-form.select name="branch" label="Cabang" :options="['' => 'Semua'] + $branches->pluck('name', 'uuid')->all()" :value="$filters['branch'] ?? ''" /></div><div class="col-sm-6 col-lg-2"><x-form.select name="sort" label="Urutkan" :options="['newest' => 'Terbaru', 'oldest' => 'Terlama', 'name' => 'Nama A-Z']" :value="$filters['sort'] ?? 'newest'" /></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary">Terapkan</button><a href="{{ route('members.index') }}" class="btn btn-outline-secondary">Reset</a></div></form></x-card>
    @if($members->isEmpty())<x-empty-state title="Belum ada anggota" message="Tambahkan anggota pertama atau ubah filter pencarian Anda.">@can('create', [App\Models\FamilyMember::class, $family])<a href="{{ route('members.create') }}" class="btn btn-primary mt-3">Tambah anggota</a>@endcan</x-empty-state>@else
    <div class="card d-none d-md-block"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Foto</th><th>Nama</th><th>Panggilan</th><th>Gender</th><th>Lahir</th><th>Status</th><th></th></tr></thead><tbody>@foreach($members as $member)<tr><td>@include('members.partials.avatar', ['member' => $member])</td><td><a href="{{ route('members.show', $member) }}" class="fw-semibold text-decoration-none">{{ $member->is_alive ? '' : '† ' }}{{ $member->full_name }}</a></td><td>{{ $member->nickname ?: '—' }}</td><td>{{ $member->gender === 'male' ? 'Laki-laki' : ($member->gender === 'female' ? 'Perempuan' : '—') }}</td><td>{{ $member->birth_date?->format('d M Y') ?? '—' }}</td><td><x-badge :variant="$member->is_alive ? 'success' : 'secondary'">{{ $member->is_alive ? 'Hidup' : 'Wafat' }}</x-badge></td><td><a href="{{ route('members.show', $member) }}" class="btn btn-sm btn-outline-primary">Detail</a></td></tr>@endforeach</tbody></table></div></div>
    <div class="d-md-none vstack gap-3">@foreach($members as $member)<x-card><div class="d-flex gap-3">@include('members.partials.avatar', ['member' => $member])<div class="min-width-0"><a href="{{ route('members.show', $member) }}" class="fw-bold text-decoration-none">{{ $member->is_alive ? '' : '† ' }}{{ $member->full_name }}</a><div class="text-secondary small">{{ $member->nickname ?: 'Tanpa nama panggilan' }} · {{ $member->branch?->name ?: 'Tanpa cabang' }}</div><x-badge :variant="$member->is_alive ? 'success' : 'secondary'" class="mt-2">{{ $member->is_alive ? 'Hidup' : 'Wafat' }}</x-badge></div></div></x-card>@endforeach</div>
    <div class="mt-4">{{ $members->links() }}</div>@endif
</x-layouts.app>
