<x-layouts.app :title="$member->full_name">
    @if(session('status'))<x-alert variant="success">{{ session('status') }}</x-alert>@endif
    @if($errors->any())<x-alert variant="danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div class="d-flex gap-3 align-items-center">@include('members.partials.avatar', ['member' => $member])<div><a href="{{ route('members.index') }}" class="small">← Direktori anggota</a><h1 class="h2 mb-1"><x-member-name :member="$member" /></h1><p class="text-secondary mb-0">{{ $member->nickname ? $member->nickname.' · ' : '' }}{{ $member->branch?->name ?: 'Tanpa cabang' }}</p></div></div><div class="d-flex gap-2">@can('update', $member)<a href="{{ route('members.edit', $member) }}" class="btn btn-primary">Edit anggota</a>@endcan @can('delete', $member)<form method="POST" action="{{ route('members.destroy', $member) }}" onsubmit="return confirm('Hapus anggota ini? Tindakan ini tidak dapat dibatalkan.')">@csrf @method('DELETE')<input type="hidden" name="confirm" value="1"><button class="btn btn-outline-danger">Hapus</button></form>@endcan</div></div>
    <div class="row g-4">
        <div class="col-lg-4 vstack gap-4"><x-card title="Profil"><dl class="row mb-0"><dt class="col-5">Status</dt><dd class="col-7"><x-badge :variant="$member->is_alive ? 'success' : 'secondary'">{{ $member->is_alive ? 'Hidup' : 'Wafat' }}</x-badge></dd><dt class="col-5">Gender</dt><dd class="col-7">{{ $member->gender === 'male' ? 'Laki-laki' : ($member->gender === 'female' ? 'Perempuan' : '—') }}</dd><dt class="col-5">Agama</dt><dd class="col-7">{{ ['islam' => 'Islam', 'christian' => 'Kristen', 'catholic' => 'Katolik', 'hindu' => 'Hindu', 'buddhist' => 'Buddha', 'confucian' => 'Konghucu', 'belief' => 'Penghayat kepercayaan', 'other' => 'Lainnya'][$member->religion] ?? '—' }}</dd><dt class="col-5">Lahir</dt><dd class="col-7">{{ $member->birth_place ?: '—' }}{{ $member->birth_date ? ', '.$member->birth_date->format('d M Y') : '' }}</dd>@unless($member->is_alive)<dt class="col-5">Wafat</dt><dd class="col-7">{{ $member->death_place ?: '—' }}{{ $member->death_date ? ', '.$member->death_date->format('d M Y') : '' }}</dd>@endunless</dl></x-card>
            @can('inviteAccount', $member)<x-card title="Akun anggota"><p class="small text-secondary">Kirim tautan aman agar anggota membuat password dan mengelola profilnya sendiri.</p>@if($accountInvitation)<p class="small"><strong>Undangan terakhir:</strong> {{ $accountInvitation->email }}<br>{{ $accountInvitation->accepted_at ? 'Sudah diterima' : ($accountInvitation->trashed() ? 'Digantikan atau dibatalkan' : ($accountInvitation->expires_at->isPast() ? 'Kedaluwarsa' : 'Menunggu hingga '.$accountInvitation->expires_at->format('d M Y H:i'))) }}</p>@endif<form method="POST" action="{{ route('members.account-invitations.store', $member) }}" class="vstack gap-3">@csrf<x-form.input name="email" type="email" label="Email anggota" required /><button class="btn btn-primary" type="submit">Kirim undangan</button></form></x-card>@else@if($member->user)<x-card title="Akun anggota"><p class="mb-0"><x-badge variant="success">Akun terhubung</x-badge>@if($member->user_id === auth()->id())<br><span class="small text-secondary">{{ $member->user->email }}</span>@endif</p></x-card>@endif@endcan
        </div>
        <div class="col-lg-8 vstack gap-4"><x-card title="Biografi">@if($member->biography)<p class="mb-0 text-preline">{{ $member->biography }}</p>@else<x-empty-state title="Belum ada biografi" message="Tambahkan kisah hidup anggota ini melalui halaman edit." />@endif</x-card>
            <x-card title="Relasi dasar">@forelse($relationships as $relationship)@php($other = $relationship->source_member_id === $member->id ? $relationship->targetMember : $relationship->sourceMember)<div class="d-flex justify-content-between border-bottom py-2"><a href="{{ route('members.show', $other) }}"><x-member-name :member="$other" /></a><x-badge variant="secondary">{{ ucfirst($relationship->relationship_type) }}</x-badge></div>@empty<x-empty-state title="Belum ada relasi" message="Relasi dasar anggota belum dicatat." />@endforelse</x-card>
            <div class="row g-4"><div class="col-md-4"><x-card title="Foto"><x-empty-state title="Belum ada foto" message="Foto yang menandai anggota akan tampil di sini." /></x-card></div><div class="col-md-4"><x-card title="Artikel"><x-empty-state title="Belum ada artikel" message="Artikel terkait anggota akan tampil di sini." /></x-card></div><div class="col-md-4"><x-card title="Timeline"><x-empty-state title="Belum ada aktivitas" message="Aktivitas anggota akan tampil di sini." /></x-card></div></div>
        </div>
    </div>
</x-layouts.app>
