<x-layouts.app title="Profil & Keamanan">
    <div class="mb-4"><h1 class="h2 mb-1">Profil & keamanan</h1><p class="text-secondary mb-0">Kelola identitas, preferensi, password, dan sesi akun Anda.</p></div>
    @if(session('status'))<x-alert variant="success">{{ session('status') }}</x-alert>@endif
    <ul class="nav nav-tabs mb-4" role="tablist">
        @foreach(['profile' => 'Profil', 'notifications' => 'Notifikasi', 'security' => 'Keamanan', 'sessions' => 'Sesi aktif'] as $id => $label)<li class="nav-item" role="presentation"><button class="nav-link {{ $loop->first ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#{{ $id }}" type="button" role="tab" aria-controls="{{ $id }}">{{ $label }}</button></li>@endforeach
    </ul>
    <div class="tab-content">
        <section class="tab-pane fade show active" id="profile" role="tabpanel"><div class="row g-4">
            <div class="col-lg-4"><x-card title="Avatar"><div class="text-center mb-3">@if($user->avatar)<img src="{{ Storage::url($user->avatar) }}" class="profile-avatar" alt="Avatar {{ $user->name }}">@else<div class="profile-avatar member-avatar-placeholder mx-auto" aria-hidden="true">{{ Str::upper(Str::substr($user->name, 0, 1)) }}</div>@endif</div><form method="POST" action="{{ route('profile.avatar') }}" enctype="multipart/form-data">@csrf<label class="form-label" for="avatar">Foto JPG, PNG, atau WebP (maks. 5 MB)</label><input class="form-control @error('avatar') is-invalid @enderror" id="avatar" name="avatar" type="file" accept="image/jpeg,image/png,image/webp" required>@error('avatar')<div class="invalid-feedback">{{ $message }}</div>@enderror<x-button class="mt-3" type="submit">Unggah avatar</x-button></form></x-card></div>
            <div class="col-lg-8"><x-card title="Data profil"><form method="POST" action="{{ route('profile.update') }}" class="row g-3">@csrf @method('PUT')<div class="col-md-6"><x-form.input name="name" label="Nama" :value="$user->name" required /></div><div class="col-md-6"><x-form.input name="phone" label="Nomor HP" :value="$user->phone" /></div><div class="col-12"><x-form.input name="email" type="email" label="Email" :value="$user->email" required help="Mengubah email akan meminta password dan mengulang verifikasi." /></div><div class="col-12"><x-form.input name="current_password" type="password" label="Password saat ini" help="Wajib hanya bila mengubah email." autocomplete="current-password" /></div><div class="col-12"><x-button type="submit">Simpan profil</x-button></div></form></x-card></div>
        </div></section>
        <section class="tab-pane fade" id="notifications" role="tabpanel"><x-card title="Preferensi notifikasi"><form method="POST" action="{{ route('profile.preferences') }}" class="vstack gap-3">@csrf @method('PUT')@php($preferences = $user->notification_preferences ?? [])@foreach(['email_events' => 'Email acara keluarga', 'email_birthdays' => 'Email ulang tahun', 'email_articles' => 'Email artikel baru', 'in_app_activity' => 'Aktivitas keluarga di aplikasi'] as $key => $label)<div class="form-check form-switch"><input type="hidden" name="{{ $key }}" value="0"><input class="form-check-input" type="checkbox" role="switch" id="{{ $key }}" name="{{ $key }}" value="1" @checked($preferences[$key] ?? true)><label class="form-check-label" for="{{ $key }}">{{ $label }}</label></div>@endforeach<x-button type="submit">Simpan preferensi</x-button></form></x-card></section>
        <section class="tab-pane fade" id="security" role="tabpanel"><x-card title="Ubah password"><form method="POST" action="{{ route('profile.password') }}" class="row g-3">@csrf @method('PUT')<div class="col-12"><x-form.input name="current_password" type="password" label="Password saat ini" autocomplete="current-password" required /></div><div class="col-md-6"><x-form.input name="password" type="password" label="Password baru" autocomplete="new-password" required /></div><div class="col-md-6"><x-form.input name="password_confirmation" type="password" label="Konfirmasi password" autocomplete="new-password" required /></div><div class="col-12"><x-button type="submit">Ubah password</x-button></div></form></x-card></section>
        <section class="tab-pane fade" id="sessions" role="tabpanel"><x-card title="Sesi aktif">@forelse($sessions as $session)<div class="border-bottom py-3"><div class="d-flex justify-content-between gap-2"><strong>{{ $session->ip_address ?: 'IP tidak tersedia' }}</strong>@if($session->is_current)<x-badge variant="success">Sesi ini</x-badge>@endif</div><div class="small text-secondary text-break">{{ $session->user_agent ?: 'Perangkat tidak dikenal' }}</div><div class="small text-secondary">Aktif {{ $session->last_active_at->diffForHumans() }}</div></div>@empty<x-empty-state title="Informasi sesi tidak tersedia" message="Sesi aktif akan tercatat saat penyimpanan sesi database digunakan." />@endforelse</x-card></section>
    </div>
</x-layouts.app>
